### ISSUE TITLE
User: Don't know how much filing and court costs would be

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-ALAffidavitOfIndigency#11]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `email status`
What was confusing | Don't know how much filing and court costs would be
Other information | 
Variable being sought | `email_status`
Package version | `0.0.17`

**Comment by nonprofittechy** [comment]
We can certainly add some links to the filing costs for various courts
