### ISSUE TITLE
Need help letting Clerk know it's a new case

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-ALAffidavitOfIndigency#14]
## What best describes you?

Person needing help

## User feedback:  
> I didnt see a place to let the court or clerk know that this new case I just printed out the paperwork and it will be mailed out tomorrow 7-10-21 thats why I didnt know a docket # I dont have one yet thank you.

Question id: `final download`

Variable being sought: `download`
Package version | `0.0.17`

**Comment by nonprofittechy** [comment]
I think this is clear enough already, actually. Possibly clarified after this error report:

![image](https://user-images.githubusercontent.com/7645641/204616334-c24b1b54-ae88-4197-af60-7a5ec2262169.png)

We'll want to deprecate this as a standalone form at some point.
