### ISSUE TITLE
ID basic questions intro screen: 
User feedback: something
(`al_intro_screen`)

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-ALAffidavitOfIndigency#38]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `basic questions intro screen`
Details | Do I have to sign the affidavit? 
Variable being sought | `al_intro_screen`
Package version | `2.1.1`
Filename | `docassemble.ALAffidavitOfIndigency:data/questions/affidavit.yml`

**Comment by BryceStevenWilley** [comment]
Signing the form is missing from the 3 initial steps that we have on our default intro. I'm not sure if it's necessary to add ti though, as we'll still guide you through the signing steps on the same device you have. Gonna close this.
