### ISSUE TITLE
ID intro: 
User feedback: bug
(`aff_of_indigency_intro`)

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-ALAffidavitOfIndigency#48]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `intro`
Details | Testing another feedback implementation, to make sure it saves on the server this time.
Variable being sought | `aff_of_indigency_intro`
Package version | `2.1.2`
Maturity target | Level 1.5 - it works as-is, but this is a significant plain language issue
Filename | `docassemble.ALAffidavitOfIndigency:data/questions/affidavit.yml`

**Comment by BryceStevenWilley** [comment]
It does save things, yay!
